# Generated by Django 2.2.6 on 2019-11-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0002_auto_20191127_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(),
        ),
    ]
