# Generated by Django 2.2.6 on 2019-11-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0005_workout_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['date']},
        ),
    ]
